#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer

sudo apt update
sudo apt install haproxy -y
sudo cp /etc/default/haproxy /etc/default/haproxy.bkp
echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo sed -i "$ a\\\nlisten bakxy\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 172285-web-01 34.207.121.66:80 check\n\tserver 172285-web-02 18.206.192.99:80 check" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
