#!/usr/bin/env bash
#  Bash script that displays the content of the file /etc/passwd
# displays:
	# username
	# user id
	# Home directory path for the user

while FILE= read -r passwd;
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
