#!/usr/bin/env bash
# Bash script that loops from 1 to 10
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

iteration=1

while (( iteration <= 10 ))
do
    if [ "$iteration" -eq "4" ]
    then
        echo "bad luck"
    elif [ "$iteration" -eq "8" ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi

    iteration=$(( iteration + 1 ))
done
