#!/usr/bin/env bash
# Apache to run on the container and to return a page 
# containing Hello Holberton when querying the root of it

echo 'Hello Holberton' > /var/www/html/index.html
service apache2 start
